version: '3'

services:
  postgresql:
    image: postgres
    container_name: OwlTOP
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root1
      - POSTGRES_PASSWORD=root1
      - POSTGRES_DB=root1
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-OwlTOP
    ports:
      - '6379-6379'